version: "3.8"
services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        image: laravel-app
        container_name: laravel_app
        restart: always
        ports:
            - "$PORT:$PORT"
        environment:
            APP_ENV: production
            APP_DEBUG: "false"
            APP_KEY: ${APP_KEY}
            APP_URL: ${APP_URL}
            PORT: ${PORT}
            DB_CONNECTION: mysql
            DB_HOST: ${DB_HOST}
            DB_PORT: ${DB_PORT}
            DB_DATABASE: ${DB_DATABASE}
            DB_USERNAME: ${DB_USERNAME}
            DB_PASSWORD: ${DB_PASSWORD}
