version: "3.8"

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        image: laravel-app
        container_name: laravel_app
        restart: always
        ports:
            - "8080:8080" # Fijo a 8080 para Railway
        volumes:
            - .:/var/www/html
        environment:
            APP_ENV: production
            APP_DEBUG: "false"
            APP_KEY: "base64:GtWER1olYJc5uGl12vHdtkEylA0i7fh7lgFBn5Du9xE="
            APP_URL: https://apiprueba1-production.up.railway.app
            PORT: 8080 # Asegura que el contenedor escuche en el puerto esperado
