version: "3.8"

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        image: laravel-app
        container_name: laravel_app
        restart: always
        ports:
            - "8080:${PORT}" # Asegura que el puerto externo coincide con la variable dinámica
        volumes:
            - .:/var/www/html
            - ./storage:/var/www/html/storage
        environment:
            APP_ENV: production
            APP_DEBUG: "false"
            APP_KEY: "base64:GtWER1olYJc5uGl12vHdtkEylA0i7fh7lgFBn5Du9xE="
            APP_URL: https://apiprueba1-production.up.railway.app
            PORT: 8080 # Railway usa esta variable para asignar el puerto dinámico
